Repository ant-design/pro-table, pull requests merged in 2019-12, with the labels that each got.

#31 feat: add dnd sort
  README.en_US.md
  README.md
  docs/api.md
  package.json
  src/Table.tsx
  src/component/columnSetting/DndItem.tsx
  src/component/columnSetting/index.less
  src/component/columnSetting/index.tsx
  src/component/toolBar/index.tsx
  src/component/util.tsx
  src/useFetchData.tsx
  tests/__tests__/__snapshots__/index.test.tsx.snap
Labels: enhancement

#34 bugfix: fix filter not work when value is 0 (number)
  src/Table.tsx
Labels: bugfix

#37 feat: wrap search buttons in a Form.Item
  src/Form/index.tsx
Labels: enhancement

#40 refactoring: refactoring the action API
  README.en_US.md
  README.md
  docs/api.md
  docs/demo/single.tsx
  package.json
  src/Form/index.tsx
  src/Table.tsx
  src/component/columnSetting/index.tsx
  src/component/util.tsx
  src/container.tsx
  src/index.tsx
  src/useFetchData.tsx
Labels: refactoring

#45 feat: add intl
  .eslintrc.js
  docs/demo/single.tsx
  src/Form/index.tsx
  src/Table.tsx
  src/component/columnSetting/index.tsx
  src/component/intlContext/index.tsx
  src/component/toolBar/FullscreenIcon.tsx
  src/component/toolBar/index.tsx
  src/index.tsx
  src/locale/en_US.tsx
  src/locale/zh_CN.tsx
Labels: enhancement

#61 doc: fix minor syntax errors.
  docs/search.md
Labels: doc
